import { NextResponse } from "next/server";
import { createSupabaseServer, createSupabaseAdmin } from "@/lib/db/supabase-server";
import JSZip from "jszip";

export async function GET(
  request: Request,
  { params }: { params: Promise<{ projectId: string }> }
) {
  try {
    const supabase = await createSupabaseServer();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { projectId } = await params;

    // Verify project belongs to user
    const { data: project, error: projectError } = await supabase
      .from("projects")
      .select("name, status")
      .eq("id", projectId)
      .eq("user_id", user.id)
      .single();

    if (projectError || !project) {
      return NextResponse.json({ error: "Project not found or access denied" }, { status: 403 });
    }

    // Get all files from DB
    const supabaseAdmin = await createSupabaseAdmin();
    const { data: files, error: filesError } = await supabaseAdmin
      .from("project_files")
      .select("file_path, content")
      .eq("project_id", projectId)
      .eq("status", "approved");

    if (filesError || !files || files.length === 0) {
      return NextResponse.json({ error: "No files found for this project" }, { status: 404 });
    }

    // Package as ZIP using JSZip
    const zip = new JSZip();

    for (const file of files) {
      if (file.content) {
        zip.file(file.file_path, file.content);
      }
    }

    // Add README.md at root
    const readmeContent = `# ${project.name}

Generated by NEXUS AI (Multi-AI coding platform)

## Getting Started

First, install dependencies:
\`\`\`bash
npm install
\`\`\`

Then, run the development server:
\`\`\`bash
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

This project was built automatically. Review the code before deploying to production.
`;
    zip.file("README.md", readmeContent);

    // Generate zip content as a buffer
    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    // Return ZIP response
    const headers = new Headers({
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${project.name.toLowerCase().replace(/\s+/g, "-")}.zip"`,
    });

    return new Response(new Uint8Array(zipBuffer), { headers });
  } catch (error) {
    console.error("ZIP download error:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
export const dynamic = "force-dynamic";
export const revalidate = 0;
export interface RouteParams {
  params: {
    projectId: string;
  };
}
